services:
  - type: web
    name: ajeita
    env: static
    buildCommand: ""
    staticPublishPath: ./
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /**/*.html
        name: Cache-Control
        value: no-store, no-cache, must-revalidate, max-age=0
      - path: /
        name: Cache-Control
        value: no-store, no-cache, must-revalidate, max-age=0
    routes:
      - type: redirect
        source: /(.*)
        destination: /index.html
        permanent: false
        condition:
          - type: file-not-found
            value: true

  - type: web
    name: ajeita-backend-pix
    env: node
    rootDir: backend-pix-ajeita
    buildCommand: npm install
    startCommand: node server.js
    region: sao-paulo
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
